### ISSUE TITLE
Support responsiveArray

### ISSUE THREAD

**Issue by sebtoombs** [wayfair/rainbow-sprinkles#124]
Hey @roginfarrer would you be interested in a PR to add support for `responsiveArray`?

## Problem Statement

Currently, rainbow-sprinkles does not support the `responsiveArray` property when using `defineProperties`. See Vanilla-Extract/sprinkles: https://vanilla-extract.style/documentation/packages/sprinkles/#responsivearray

## Proposed Solution

See draft PR: https://github.com/wayfair/rainbow-sprinkles/pull/123

**Comment by roginfarrer** [comment]
I'm not a fan of the `responsiveArray` syntax. I think it's illegible to those unfamiliar with the syntax, and it's very difficult to change or introduce new breakpoints without breaking existing implementations. I'm also concerned about introducing an additional level of complexity to the types, which are already very complicated due to merging static and dynamic properties. So I'd be worried about maintaining this in the future.

Thanks for the issue and PR, but I'm going to say no for now.
