### ISSUE TITLE
Ability to map dynamic properties values

### ISSUE THREAD

**Issue by aspirisen** [wayfair/rainbow-sprinkles#140]
## Problem Statement

Hello, first of all I would like to thank for creating such amazing library!  
I am not sure if such feature already exists, if not maybe it would be nice to have it.

You can define dynamic properties via `defineProperties`. However, the values for css variable are passed as-is. It would be nice if you could intercept this value and somehow change it. For example you may want to convert `px` to `rem` before setting final value

## Proposed Solution

It is a rough suggestion to demonstrate the idea:
```
import { rem } from 'polished'
import { createRainbowSprinkles, defineProperties } from 'rainbow-sprinkles'

const layoutProperties = defineProperties({
    dynamicProperties: {
        width: value => (typeof value === 'number' ? rem(value) : value),
    },
    shorthands: {},
})
```

Technically I can use `rem`  in react component, but having such convertions in style definitions is pretty handy. Also, the consumer do not need to import `polished` and `rem` approach is enforced by this approach.

**Comment by roginfarrer** [comment]
Thanks!

I think this is already technically possible if you compose the `rainbowSprinkles` runtime function into a new function that handles this case.

```typescript
function customSprinkles(props: Parameters<typeof rainbowSprinkles>[0]) {
  return rainbowSprinkles({
    ...props,
    width: typeof props.width === 'number' ? rem(props.width) : props.width
  })
```

You would need to serialize the function with [addFunctionSerializer](https://vanilla-extract.style/documentation/api/add-function-serializer/) in order to export it from a `.css.ts` file.

I'd erring on keeping this library focused on the generation of the styles instead of intercepting the argument values, for which there's already solutions to do so. There's also a potential overlap with this kind of API and one that would support #37
