### ISSUE TITLE
Support responsiveArray

### ISSUE THREAD

**Issue by chef-jojo** [wayfair/rainbow-sprinkles#56]
## Problem Statement
allow `responsiveArray` option in `defineProperties`.

probably need to attach the responsiveArray into each config, and loop `propValue` if it's array

**Comment by roginfarrer** [comment]
Thanks for the PR! I didn't add support for `responsiveArray` because I think it's a worse API than the object syntax, which is more explicit. I think adding `responsiveArray` could make the library considerably more complex. 

I might be open to this feature in the future, after we hit a stable 1.0.0.
